# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Multiscale Modeling, Simulation & Integrated eXperimentation (MOSAIX) Lab
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Pruthul Kokkada Ravindranath"
  avatar : "/assets/images/ProfilePic.jpg"
  bio    : "Dr. Pruthul Kokkada Ravindranath is an Assistant Professor in the Aerospace and Mechanical Engineering Department at Saint Louis University. Previously, he was a research scientist at Baylor University in the Scientific Innovations in Complex Engineering Materials Group within the Department of Mechanical Engineering. He obtained his Ph.D. in Aerospace Engineering and Mechanics from the University of Alabama, where his research focused on the atomic-scale study of carbon-based materials. Following the completion of his doctorate, he served as Graduate Faculty at the University of Alabama until 2020. Funded by the U.S. Army and having developed patented technologies certified by the Federal Aviation Administration (FAA), his research integrates computational and experimental solid mechanics. With extensive experience in advanced composite materials, polymer and metal additive manufacturing, molecular dynamics, finite element analysis, non-destructive evaluation, and materials characterization, he employs a closely coupled experimental and theoretical approach to advance the multifunctional properties of composite materials. His work has applications across the aerospace, mechanical, and materials industries."
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/pruthulkokkada/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?hl=en&user=lQvqdqEAAAAJ"
    #- label: "GitHub"
     # icon: "fab fa-fw fa-github"
      #url: "https://github.com/"
    #- label: "Instagram"
     # icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/"

#footer:
  #links:
    #- label: "Twitter"
      #icon: "fab fa-fw fa-twitter-square"
     # url: "https://twitter.com/"
    #- label: "GitHub"
     # icon: "fab fa-fw fa-github"
      #url: "https://github.com/"
   # - label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
     # url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
